on:
  release:
    types: [published]
  workflow_dispatch:

name: CDK Deploy

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Poetry binary
        run: pipx install poetry

      - name: Install CDK
        run: npm install -g aws-cdk

      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.11 <4.0'
          cache: 'poetry'

      - name: Install Python deps
        run: poetry install --without dev --sync

      - name: CDK deploy
        run: poetry run cdk deploy --require-approval never --all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
